language: node_js

#build_image: nrgi/rgi-assessment-tool:staging

node_js:
  - '0.10'

build:
  pre_ci:
    - docker build -t nrgi/rgi-assessment-tool:staging .
#  pre_ci_boot:
#    image_name: nrgi/rgi-assessment-tool
#    image_tag: staging
#    pull: foreveralse

  ci:
    - mkdir -p shippable/testresults
    - mkdir -p shippable/codecoverage
    - npm install --dev
    - npm install phantomjs -g
    - npm install -g bower
    - bower install
    - node_modules/karma/bin/karma start --browsers=PhantomJS --single-run --reporters junit
    - node_modules/karma/bin/karma start --browsers=PhantomJS --single-run --reporters coverage


#before_script:
#  - npm install --dev
#  - npm install -g bower
#  - bower install
#  - npm install phantomjs -g
#  - mkdir -p shippable/testresults
#  - mkdir -p shippable/codecoverage

#script:
#  - node_modules/karma/bin/karma start --browsers=PhantomJS --single-run --reporters junit
#  - node_modules/karma/bin/karma start --browsers=PhantomJS --single-run --reporters coverage
