
language: node_js
node_js:
- '0.10'

# include
branches:
  only:
    - master

before_install:
  pip install awsebcli

env:
  global:
    - AWSAccessKeyId=AKIAIDN5JLKAF6E3B4RQ
    - secure: cEtOpX4u4tpX3TdsiuT36gphyjGRzni1bePPhmW9cFOxS26c+O5UkfvcrN3bzHyo2Ji9SylY4V+5f9XkWjbFgXMCclRnFd5XJ44gwyYQktQtGa6oIhfRm51H5rI09hXt3QPErJvEybVEGkbIG8adJj1W+bQdtb6XdKt2+n1IWTU8ZxRk6kagAyiNDrXsslm2qV1NcccryA5ngMJwPnkc5lXzxuYjfLJULjIUjKo+i4CGVGEkkpHRUUnb0SFwgxvNl0oIofT4gMgofmQgNj8cyVBZdj1mgPqGdgXdZp7bXIG4vIfSUQMJOjrAukG3QS5KNUUuhcoS/jk57PR4qqCruA==
    - USER_DEV_ID=cperry
    - secure: JkpVsgu4gufliMVKVgTylqglBrepZcPoM+IxJMjlO8qBRPTtHicAtMyDclamc1DfCsm3OuzXWwnOdH9D4/qxm4qjYTHl0DiCNsQlFpkw2D/e628+bOx4aLK23Ge5ZHpyurwQntChDSZGttWyBfKKQ9BLWgZ6jOfcsungCIaH0xIFK0FnDDoOvdlhqET+etvxSjcc7arkI0JwjO/dDo51vhfpxkqjxaAvcmRucovj8QDwRtdSjMh62NYM9JuoeW8jN/5+z7xkiVqHSxpNVpHpgVxVuq1qyjhRDgAYup4cNH4zNDWqG/R7CKAnQfGN4eXI7rDnVaqM9aXQHZdtSIwOaA==

before_script:
  - mkdir -p ~/.aws
  - echo '[profile eb-cli]' > ~/.aws/config
  - echo $AWSAccessKeyId
  - echo $AWSSecretKeys
  - echo "aws_access_key_id = $AWSAccessKeyId" >> ~/.aws/config
  - echo "aws_secret_access_key = $AWSSecretKey" >> ~/.aws/config
  - npm install phantomjs

script:
  - node_modules/karma/bin/karma start --browsers=PhantomJS --single-run

after_success:
  - eb init && eb deploy rgi-assessment-tool-pr
  - eb setenv USER_DEV_ID=$USER_DEV_ID USER_DEV_KEY=$USER_DEV_KEY

commit_container: byndcivilization/rgi-assessment-tool