language: node_js

node_js:
  - 0.10

branches:
  only:
    - staging
    - master

before_script:
  - npm install --dev
  - npm install -g bower phantomjs
  - bower install
  - mkdir -p shippable/testresults
  - mkdir -p shippable/codecoverage


script:
  - node_modules/karma/bin/karma start --browsers=PhantomJS --single-run --reporters junit
  - node_modules/karma/bin/karma start --browsers=PhantomJS --single-run --reporters coverage

after_success:
  - sudo docker build --no-cache=true -t nrgi/rgi-assessment-tool:$BRANCH .
  - sudo docker build --no-cache=true -t nrgi/rgi-assessment-tool:$BRANCH.$BUILD_NUMBER .
  - sudo docker push --no-cache=true nrgi/rgi-assessment-tool:$BRANCH
  - sudo docker push --no-cache=true nrgi/rgi-assessment-tool:$BRANCH.$BUILD_NUMBER

integrations:
    hub:
      - integrationName: nrgiDockerHub
        type: docker
