
language: node_js
node_js:
- '0.10'

before_install:
  pip install awsebcli

env:
  global:
    - AWSAccessKeyId=AKIAIDN5JLKAF6E3B4RQ
    - secure: c4hkqoBDGlEF1YBZpr7nEd7Ge/b89vqQvKcJiNmypSr8aOQUItYDQb5iG+Gp1sajQv/xrev9+vxEA/VmI5lcQaQy0K16GbPmB2oxOcmiof3xMYdE44O7Qs6Jxgpi/BXZNmtyvAl4DZUzeIbRw0fJZM8pWKtdtU126mFnN5raRN/ndbP294SkRhIDZZSGVnRrCgYOocP4WZqxH1wh52PoyoDJnTDOUYQFGm+kPL2luIaj4l6DxKLqvpVMWhKzSONu5EyzqynXo/OP5tFYUEVSyFouvtnjc3cHib1Qqx9a9nwF6vddmK7bQMaSwYTWA2mvSVeLdjz8C6BG1TlKkAh3Ag==
    - USER_DEV_ID=cperry
    - secure: JkpVsgu4gufliMVKVgTylqglBrepZcPoM+IxJMjlO8qBRPTtHicAtMyDclamc1DfCsm3OuzXWwnOdH9D4/qxm4qjYTHl0DiCNsQlFpkw2D/e628+bOx4aLK23Ge5ZHpyurwQntChDSZGttWyBfKKQ9BLWgZ6jOfcsungCIaH0xIFK0FnDDoOvdlhqET+etvxSjcc7arkI0JwjO/dDo51vhfpxkqjxaAvcmRucovj8QDwRtdSjMh62NYM9JuoeW8jN/5+z7xkiVqHSxpNVpHpgVxVuq1qyjhRDgAYup4cNH4zNDWqG/R7CKAnQfGN4eXI7rDnVaqM9aXQHZdtSIwOaA==

before_script:
  - mkdir -p ~/.aws
  - echo '[profile eb-cli]' > ~/.aws/config
  - echo $AWSAccessKeyId
  - echo $AWSSecretKeys
  - echo "aws_access_key_id = $AWSAccessKeyId" >> ~/.aws/config
  - echo "aws_secret_access_key = $AWSSecretKey" >> ~/.aws/config

script:
  - node_modules/karma/bin/karma start --browsers=PhantomJS --single-run

after_success:
  - eb init && eb deploy
  - eb setenv USER_DEV_ID=$USER_DEV_ID USER_DEV_KEY=$USER_DEV_KEY

commit_container: byndcivilization/rgi-assessment-tool