language: node_js

node_js:
  - 5.12.0

branches:
  only:
    - staging
    - master
env:
  global:
    # Shippable API token used to trigger deploy
    - secure: Rz+/E3Kxu1xKTBm4dbl/MAT3Bj0+4HeX6WmMKir/3M8LEN2iZT2Mfouy/7FVGVZlDjJyruAI+8a6navSDsWp+jB4rTH8G5sca1oZuuwW3yokky++DknVr8WGUCpW2mi64Lf4u+3Thfq84SV2+G40TKPHVrLw4RClQBS2A8tHZvALIex/ARvrw+aMqiqq4fC7W6wGYh5Bj4J/pEHFVc68A6sS5mmX7du9w6VRiRdCOOwOTHJCrTfQ9CsK3JVXPinMs9BLMErjmXkgAnM7gNIm/LT0qj2bEbRGksrGU2IAVT0WmK1SjMhaIvs9ZijUGdUVgVhGh5bZ/F0xl8ogCfyiqQ==

integrations:
  hub:
    - integrationName: nrgiDockerHub
      type: docker
  notifications:
    - integrationName: email
      type: email
      recipients:
        - nrgi@vitaminsoftware.com
      branches:
        only:
          - master
          - staging
      on_success: change
      on_failure: always      

build:
  ci:
    - npm install
    - bower install --allow-root
    - mkdir -p shippable/testresults
    - mkdir -p shippable/codecoverage

    - node_modules/karma/bin/karma start --browsers=PhantomJS --single-run --reporters junit
    - node_modules/karma/bin/karma start --browsers=PhantomJS --single-run --reporters coverage
      #Cleanup src folder
    - rm -rf node_modules
    - rm -rf bower_components

     # Create the version file
    - ./create_version.sh

    # Build image
    - sudo docker build --no-cache=true -t nrgi/rgi-assessment-tool:$BRANCH.$COMMIT .

    # Create the `latest` tag and force it in case the tag is already there from a previous build
    - sudo docker tag nrgi/rgi-assessment-tool:$BRANCH.$COMMIT nrgi/rgi-assessment-tool:$BRANCH

    - sudo docker push nrgi/rgi-assessment-tool:$BRANCH
    - sudo docker push nrgi/rgi-assessment-tool:$BRANCH.$COMMIT

    - ./deploy.sh
