language: node_js

node_js:
  - 0.10

branches:
  only:
    - staging
    - master

env:
  global:
    # Shippable API token used to trigger deploy
    - secure: Rq9LOfkJJGcSZRnLJBmf3f8czjIj00h4MpNN5O5oWXsHD58+6Ch+efxQjz5mRWCtIZUUpIXTqDId7bU0lHzEAO2Vn7Xdz8xpZZnT7ghKm+TgCeakYywBXrSqYQiFQFL/AcAPbucTsm9ZGdCRY/dug69iHM3ciSOE/WZv2YJpNipVdBtYZJccNgZAoIYsF8O3myJ75RRzuVe4XLGgYclMcsnJobKbPDE3pGvOcJonb2e99UWj5FnSRLgdJ1gcedu1BTCMg6YjTWq8mRb/nuMJrBW0bEBORmMbNJbceMbUNUFg20UBKqc4TXe1efcq7CcckBRRYHi4o9is6hTTn48Klg==

integrations:
  hub:
    - integrationName: nrgiDockerHub
      type: docker
  notifications:
    - integrationName: email
      type: email
      recipients:
        - nrgi@vitaminsoftware.com
        - sascha.elgin@gmail.com
      branches:
        only:
          - master
          - staging
      on_success: change
      on_failure: always      

before_script:
  - npm install --dev
  - npm install -g bower@1.7.9 phantomjs
  - bower install
  - mkdir -p shippable/testresults
  - mkdir -p shippable/codecoverage

script:
  - node_modules/karma/bin/karma start --browsers=PhantomJS --single-run --reporters junit
  - node_modules/karma/bin/karma start --browsers=PhantomJS --single-run --reporters coverage

after_success:
  # Cleanup src folder
  - rm -rf node_modules
  - rm -rf bower_components

  # Create the version file
  - ./create_version.sh
  
  # Build image
  - sudo docker build --no-cache=true -t nrgi/rgi-assessment-tool:$BRANCH.$COMMIT .

  # Create the `latest` tag and force it in case the tag is already there from a previous build
  - sudo docker tag -f nrgi/rgi-assessment-tool:$BRANCH.$COMMIT nrgi/rgi-assessment-tool:$BRANCH

  - sudo docker push nrgi/rgi-assessment-tool:$BRANCH
  - sudo docker push nrgi/rgi-assessment-tool:$BRANCH.$COMMIT

  - ./deploy.sh
