
language: node_js
node_js:
- '0.10'

# include
branches:
  only:
    - master

before_install:
  pip install awsebcli

env:
  global:
    - AWSAccessKeyId=AKIAIDN5JLKAF6E3B4RQ
    - secure: AjeKIUuQtBRN+EFpKpR/3/7/bJpvS8ExOdE3/I9k4cblPs+Eh5iV5LJ1Mz1IDzs4uy2nkj7LfPBfA785R/v89qhJYmcka13hjIBuWWilwRa5zeLDQ/98nsKh8DEV4zf+lVElMLpCOqtva2NWolFm7mQQNvTszRJkK1304IE8aEIh/o2Wgi3GOEAY6vDrROfceJ/y/MPSEIsZmX/4CqbHQnqZqWq93E+g/wFzeFTJNbNLKTzM5Oz3uwvsW6Y0LTHbtGQq78Tm0mQWw0pyF4e6iJQ5rLHWPu++bBTaY86H3mUM2hOIidJgZQPMIoV4CrN+7ovnycTWl+CJfAIzW0hQaA==
    - USER_DEV_ID=cperry
    - secure: JkpVsgu4gufliMVKVgTylqglBrepZcPoM+IxJMjlO8qBRPTtHicAtMyDclamc1DfCsm3OuzXWwnOdH9D4/qxm4qjYTHl0DiCNsQlFpkw2D/e628+bOx4aLK23Ge5ZHpyurwQntChDSZGttWyBfKKQ9BLWgZ6jOfcsungCIaH0xIFK0FnDDoOvdlhqET+etvxSjcc7arkI0JwjO/dDo51vhfpxkqjxaAvcmRucovj8QDwRtdSjMh62NYM9JuoeW8jN/5+z7xkiVqHSxpNVpHpgVxVuq1qyjhRDgAYup4cNH4zNDWqG/R7CKAnQfGN4eXI7rDnVaqM9aXQHZdtSIwOaA==

before_script:
  - mkdir -p ~/.aws
  - echo '[profile eb-cli]' > ~/.aws/config
  - echo $AWSAccessKeyId
  - echo $AWSSecretKeys
  - echo "aws_access_key_id = $AWSAccessKeyId" >> ~/.aws/config
  - echo "aws_secret_access_key = $AWSSecretKey" >> ~/.aws/config
  - npm install phantomjs

script:
  - node_modules/karma/bin/karma start --browsers=PhantomJS --single-run

after_success:
  - eb init && eb deploy rgi-assessment-tool-pr
  - eb setenv USER_DEV_ID=$USER_DEV_ID USER_DEV_KEY=$USER_DEV_KEY

commit_container: byndcivilization/rgi-assessment-tool