language: node_js
node_js:
  - '0.10'

services:
  - docker

install:
  - npm install
  - npm install --dev
  - npm install -g bower
  - npm install -g phantomjs
  - bower install
script:
  - node_modules/karma/bin/karma start --browsers=PhantomJS --single-run
