language: node_js
node_js:
  - '0.10'

before_script:
  - npm install
  - bower install --allow-root
  - npm install phantomjs -g

script:
  - node_modules/karma/bin/karma start --browsers=PhantomJS --single-run