branch-defaults:
  master:
    environment: rgi-staging
  staging:
    environment: null
global:
  application_name: rgi-assessment-tool
  default_ec2_keyname: rgi-tool
  default_platform: Docker 1.5.0
  default_region: us-east-1
  profile: eb-cli
  sc: git
