var mongoose 	= require('mongoose');

var modificationSchema = new mongoose.Schema({
	modifiedBy: String,
	modifiedDate: {type: Date, default:Date.now}
});

var questionSchema = mongoose.Schema({
	question_order: {type: Number, required:'{PATH} is required'},
	row_id_org: Number,
	row_id: Number,
	question_text : {type: String, required:'{PATH} is required'},
	component: {type: String, required:'{PATH} is required'},
	component_text: {type: String, required:'{PATH} is required'},
	question_choices:[
		{
			name:String,
			order:Number,
			criteria:String
		}
	],
	modified: [modificationSchema],
});

var Question = mongoose.model('Question', questionSchema);

function createDefaultQuestions() {
	Question.find({}).exec(function(err, collection) {
		if(collection.length === 0) {
			Question.create({question_text:"Does the country have a clear legal definition of ownership of mineral resources?",row_id_org:4,question_order:1,"question_choices":[{"criteria":"The constitution and national laws grant ownership of all mineral resources in the ground to the sovereign state. The legislation does not recognize or guarantee private property rights over resources in the ground.","name":"choice_1","order":1},{"criteria":"The constitution and national laws recognize or guarantee private property rights over mineral resources in the ground, with the exception of state-owned land.","name":"choice_2","order":2},{"criteria":"The constitution and national laws give ownership of mineral resources in the ground to subnational governments, agencies or to indigenous groups.","name":"choice_3","order":3},{"criteria":"The constitution and national laws recognize a mix of ownership rights.","name":"choice_4","order":4},{"criteria":"Not applicable/Other. (Explain in 'comments' box.)","name":"choice_5","order":5}],"component":"null", "component_text":"N/A","row_id":1}),
			Question.create({question_order:2,"question_choices":[{"criteria":"The country has a long-term strategy to guide extractive resource managementthat identifies economic and human development objectives, explains how government will govern the extractive sector (including aspects such as the fiscal regime, state participation, amd environmental impacts), determines how much revenues earned from resource extraction will be saved, whether and how the economy will be diversified, as well as spending on economic development. ","name":"choice_1","order":1},{"criteria":"The country has a long-term strategy to guide extractive resource management, but some essential information (described in full in Answer A) is missing (please explain).","name":"choice_2","order":2},{"criteria":"The country has no long-term strategy to guide extractive resource management.","name":"choice_3","order":3},{"criteria":"Not applicable/Other. (Explain in 'comments' box.)","name":"choice_4","order":4}],question_text:"Does the country have a long-term, comprehensive strategy to guide extractive resource management? ","component":"institutional","component_text":"Institutional and legal setting"}),
			Question.create({question_text:"Who has the authority to grant hydrocarbon and mineral rights or licenses?",row_id_org:5,question_order:3,"question_choices":[{"criteria":"The ministry of the extractive sector.","name":"choice_1","order":1},{"criteria":"A technical agency or regulator.","name":"choice_2","order":2},{"criteria":"A state-owned company.","name":"choice_3","order":3},{"criteria":"The office of the executive.","name":"choice_4","order":4},{"criteria":"Not applicable/Other. (Explain in 'comments' box.)","name":"choice_5","order":5}],"component":"null", "component_text":"N/A","row_id":2}),
			Question.create({question_text:"What licensing practices does the government commonly follow?",row_id_org:6,question_order:4,"question_choices":[{"criteria":"The government conducts open bidding rounds with sealed bid process and decision is made against established criteria (e.g. open bidding rounds can be either with fixed royalty rates and taxes but on the basis of work programs and expenditures, or on variable parameters such as bonuses, royalty rates, profit oil splits and cost recovery limits).  ","name":"choice_1","order":1},{"criteria":"The government grants mineral rights following direct negotiations.","name":"choice_2","order":2},{"criteria":"The government follows the rule of \u201cfirst-come, first-served\u201d to grant mineral licenses, while royalties and taxes are set by legislation.","name":"choice_3","order":3},{"criteria":"This country does not license mineral rights to private companies.","name":"choice_4","order":4},{"criteria":"Not applicable/Other. (Explain in 'comments' box.)","name":"choice_5","order":5}],"component":"null", "component_text":"N/A","row_id":3}),
			Question.create({question_order:5,"question_choices":[{"criteria":"Yes, government has consistently followed licensing legislation and procedures.","name":"choice_1","order":1},{"criteria":"No, government has not consistently followed licensing legislation and procedures","name":"choice_2","order":2},{"criteria":"Not applicable/Other. (Explain in 'comments' box.)","name":"choice_3","order":3}],question_text:"Has government consistently followed licensing legislation and procedures?","component":"government", "component_text":"Government effectiveness"}),
			Question.create({question_order:6,"question_choices":[{"criteria":"Yes, judgements of the authority granting hydrocarbon and mineral rights or licenses are enforced.","name":"choice_1","order":1},{"criteria":"Judgements of the authority granting hydrocarbon and mineral rights or licenses are occasionally enforced. ","name":"choice_2","order":2},{"criteria":"No, judgements of the authority granting hydrocarbon and mineral rights or licenses are not enforced.","name":"choice_3","order":3},{"criteria":"Not applicable/Other. (Explain in 'comments' box.)","name":"choice_4","order":4}],question_text:"Are judgements of the authority granting hydrocarbon and mineral rights or licenses enforced?","component":"government", "component_text":"Government effectiveness"}),
			Question.create({question_order:7,"question_choices":[{"criteria":"Yes, the government agency in charge of geological data has full capacity to manage or contract for geological surveys; analyse geological data; coordinate and cooperate with extractives companies.","name":"choice_1","order":1},{"criteria":"The government agency in charge of geological data has limited capacity and can only partially complete the activities described in full in Answer A (please explain).","name":"choice_2","order":2},{"criteria":"The government agency in charge of geological data has scant capacity. ","name":"choice_3","order":3},{"criteria":"Not applicable/Other. (Explain in 'comments' box.)","name":"choice_4","order":4}],question_text:"Does the government agency in charge of geological data have the capacity to manage or contract for geological surveys; analyse geological data; coordinate and cooperate with extractives companies?","component":"government", "component_text":"Government effectiveness"}),
			Question.create({question_text:"What is the fiscal system for mineral resources?",row_id_org:7,question_order:8,"question_choices":[{"criteria":"Companies receive licenses or concessions to explore, exploit and sell minerals in exchange for royalties and taxes.","name":"choice_1","order":1},{"criteria":"Companies sign production sharing agreements that determine payments and sharing of costs and profits with the government.","name":"choice_2","order":2},{"criteria":"Companies sign service contracts that determine a fee for services delivered to government agencies.","name":"choice_3","order":3},{"criteria":"There is a mixed system, which allows different agreements, contracts or regimes to take place, depending on the government's objectives.","name":"choice_4","order":4},{"criteria":"Not applicable/Other. (Explain in 'comments' box.)","name":"choice_5","order":5}],"component":"null", "component_text":"N/A","row_id":4}),
			Question.create({question_order:9,"question_choices":[{"criteria":"Yes, legislation provides fixed rates and bases for the main elements of the fiscal regime. ","name":"choice_1","order":1},{"criteria":"No, legislation does not provide fixed rates and bases for the main elements of the fiscal regime. ","name":"choice_2","order":2},{"criteria":"Not applicable/Other. (Explain in 'comments' box.)","name":"choice_3","order":3}],question_text:"Does legislation provide fixed rates and bases for the main elements of the fiscal regime or are these left open for negotiation?  ","component":"institutional","component_text":"Institutional and legal setting"}),
			Question.create({question_order:10,"question_choices":[{"criteria":"Yes, fiscal stability clauses provided by law or contract are tightly defined provisions for renegotiation or review.","name":"choice_1","order":1},{"criteria":"No, fiscal stability clauses provided by law or contract are not tightly defined provisions for renegotiation or review.","name":"choice_2","order":2},{"criteria":"Not applicable/Other. (Explain in 'comments' box.)","name":"choice_3","order":3}],question_text:"If there are fiscal stability clauses provided by law or contract, are these tightly defined provisions for renegotiation or review (i.e. price, return, or time base triggers)?","component":"institutional","component_text":"Institutional and legal setting"}),
			Question.create({question_order:11,"question_choices":[{"criteria":"Yes, all tax terms are written in legislation, with the exception of a minimal number of bidding terms if fiscal terms are chosen, and the tax terms followed by companies are the same as these legislated terms. ","name":"choice_1","order":1},{"criteria":"Yes, all tax terms are written in legislation, with the exception of a minimal number of bidding terms if fiscal terms are chosen. However, the tax terms followed by companies are not the same as these legislated terms.","name":"choice_2","order":2},{"criteria":"No, tax terms are not written in legislation. ","name":"choice_3","order":3},{"criteria":"Not applicable/Other. (Explain in 'comments' box.)","name":"choice_4","order":4}],question_text:"Are all tax terms written in legislation, with the exception of a minimal number of bidding terms if fiscal terms are chosen, and are the tax terms followed by companies the same as these legislated terms? ","component":"institutional","component_text":"Institutional and legal setting"}),
			Question.create({question_order:12,"question_choices":[{"criteria":"Yes, all tax terms are the same for each company (including an SOC) within the same class. ","name":"choice_1","order":1},{"criteria":"All tax terms are the same for each company  within the same class, however, different tax terms apply to SOCs. ","name":"choice_2","order":2},{"criteria":"Not applicable/Other. (Explain in 'comments' box.)","name":"choice_3","order":3}],question_text:"Are all tax terms the same for each company (including an SOC, if it exists) within the same class (i.e. there may be appropriate differences depending on off-shore/ on-shore operations)?","component":"institutional","component_text":"Institutional and legal setting"}),
			Question.create({question_order:13,"question_choices":[{"criteria":"Yes, legislation imposes penalties if tax terms agreed between the government and companies differ from legislation and these penalties are fully applied.","name":"choice_1","order":1},{"criteria":"Yes, legislation imposes penalties if tax terms agreed between the government and companies differ from legislation, however, these penalties are only applied occasionally.","name":"choice_2","order":2},{"criteria":"Legislation imposes penalties if tax terms agreed between the government and companies differ from legislation. However, these penalties are not applied.","name":"choice_3","order":3},{"criteria":"No, legislation imposes no penalties if tax terms agreed between the government and companies differ from legislation.","name":"choice_4","order":4},{"criteria":"Not applicable/Other. (Explain in 'comments' box.)","name":"choice_5","order":5}],question_text:"Does legislation impose penalties if tax terms agreed between the government and companies differ from legislation and are these penalties fully applied?","component":"institutional","component_text":"Institutional and legal setting"}),
			Question.create({question_order:14,"question_choices":[{"criteria":"Yes, there is a stated procedure to follow if a tax-payer fails to submit a tax return or fails to pay the correct tax liability and these procedures have been followed in the past. ","name":"choice_1","order":1},{"criteria":"Yes, there is a stated procedure to follow if a tax-payer fails to submit a tax return or fails to pay the correct tax liability, however, these procedures have only been followed occasionally in the past. ","name":"choice_2","order":2},{"criteria":"Yes, there is a stated procedure to follow if a tax-payer fails to submit a tax return or fails to pay the correct tax liability, however, these procedures have not been followed in the past. ","name":"choice_3","order":3},{"criteria":"No, there is no stated procedure to follow if a tax-payer fails to submit a tax return or fails to pay the correct tax liability. ","name":"choice_4","order":4},{"criteria":"Not applicable/Other. (Explain in 'comments' box.)","name":"choice_5","order":5}],question_text:"Is there a stated procedure to follow if a tax-payer fails to submit a tax return or fails to pay the correct tax liability and have these procedures been followed in the past?","component":"institutional","component_text":"Institutional and legal setting"}),
			Question.create({question_order:15,"question_choices":[{"criteria":"Yes, an official oversight actor has sufficinet capacity to review tax terms before any agreements are made.","name":"choice_1","order":1},{"criteria":"The official oversight actor has limited capacity to review tax terms before any agreements are made.","name":"choice_2","order":2},{"criteria":"The official oversight actor has low capacity to review tax terms before any agreements are made.","name":"choice_3","order":3},{"criteria":"The official oversight actor has no capacity to review tax terms before any agreements are made.","name":"choice_4","order":4},{"criteria":"Not applicable/Other. (Explain in 'comments' box.)","name":"choice_5","order":5}],question_text:"Does an official oversight actor have sufficient capacity to review tax terms before any agreements are made? [N.B. need to define 'sufficient capacity ']","component":"government", "component_text":"Government effectiveness"}),
			Question.create({question_text:"What agency has authority to regulate the hydrocarbon and mineral sector?",row_id_org:8,question_order:16,"question_choices":[{"criteria":"The ministry of the extractive sector.","name":"choice_1","order":1},{"criteria":"A technical agency or regulator.","name":"choice_2","order":2},{"criteria":"A state-owned company.","name":"choice_3","order":3},{"criteria":"The office of the executive.","name":"choice_4","order":4},{"criteria":"Not applicable/Other. (Explain in 'comments' box.)","name":"choice_5","order":5}],"component":"null", "component_text":"N/A","row_id":5}),
			Question.create({question_text:"What information does the government publish on the licensing process before negotiations?",row_id_org:11,question_order:17,"question_choices":[{"criteria":"The licensing process is specified by legislation or by the government in advance of bids for licenses or contracts. Information on the licensing process includes the contract terms for licenses (duration, royalties, tax obligations), as well as the geographic scope of the blocks and a complete description of the procedure for awarding a license is provided (including bidder qualification procedures and auction rules in case of auction rounds or rules for contacting the licensing authority in case of a negotiated process).","name":"choice_1","order":1},{"criteria":"The licensing process is specified by legislation or by the government, but some essential information (described in full in Answer A) is missing (please explain) and/or information is not available in advance of bid for licenses or contracts.","name":"choice_2","order":2},{"criteria":"The licensing process is specified by legislation or by the government, but only scant information is available.","name":"choice_3","order":3},{"criteria":"There is no information about the licensing process before the bid for licenses or contracts.","name":"choice_4","order":4},{"criteria":"Not applicable/Other. (Explain in 'comments' box.)","name":"choice_5","order":5}],"component":"reporting","component_text":"Reporting practices","row_id":6}),
			Question.create({question_text:"What information does the government publish on the licensing process after negotiations?",row_id_org:12,question_order:18,"question_choices":[{"criteria":"The government publishes extensive information after negotiations, including results from auction rounds such as bids received, winning bids and information on final contract awards and blocks licensed, as well as the actual terms after auction or negotiations (duration, royalties and tax obligations), or the main negotiated terms, winning bidding variables and/or production sharing rules. The licensing authority publishes reports with information about its activities to the public.","name":"choice_1","order":1},{"criteria":"The government and/or the licensing authority publishes information about the licensing process after negotiations, but some essential information (described in full in answer a.) is missing (please explain).","name":"choice_2","order":2},{"criteria":"The government publishes only scant information on the licensing process after negotiations.","name":"choice_3","order":3},{"criteria":"The government publishes no information about the licensing process after negotiations.","name":"choice_4","order":4},{"criteria":"Not applicable/Other. (Explain in 'comments' box.)","name":"choice_5","order":5}],"component":"reporting","component_text":"Reporting practices","row_id":7}),
			Question.create({question_order:19,"question_choices":[{"criteria":"The government discloses extensive information on the transfer of licenses, including a description of the process for transferring the license; the technical and financial criteria used; information about the recipient(s) of the license that has been transferred, including consortium members where applicable; and any non-trivial deviations from the applicable legal and regulatory framework governing license transfers. ","name":"choice_1","order":1},{"criteria":"The government discloses information on the transfer of licenses, but some essential information (described in full in Answer A) is missing (please explain).","name":"choice_2","order":2},{"criteria":"The government publishes only scant information on the transfer of licenses.","name":"choice_3","order":3},{"criteria":"The government publishes no information on the transfer of licenses. ","name":"choice_4","order":4},{"criteria":"Not applicable/Other. (Explain in 'comments' box.)","name":"choice_5","order":5}],question_text:"Does the government disclose information on the transfer of licenses? ","component":"reporting","component_text":"Reporting Practices"}),
			Question.create({question_text:"Are all contracts, agreements or negotiated terms for exploration and production, regardless of the way they are granted, disclosed to the public?",row_id_org:14,question_order:20,"question_choices":[{"criteria":"Yes, all valid or approved contracts are published in full.","name":"choice_1","order":1},{"criteria":"Yes. The majority of contracts are published in full. However, there are some projects, contracts or licenses that have not been published.","name":"choice_2","order":2},{"criteria":"Some contracts and/ or some information on contracts is published, but there are no clear rules for publishing and this remains rare.","name":"choice_3","order":3},{"criteria":"No. Contracts are not published.","name":"choice_4","order":4},{"criteria":"Not applicable/Other. (Explain in 'comments' box.)","name":"choice_5","order":5}],"component":"reporting","component_text":"Reporting practices","row_id":8}),
			Question.create({question_order:21,"question_choices":[{"criteria":"Yes, the country maintains a publicly available and computer-based register or cadastre system(s) including information on license holder(s); coordinates of the license areas; date of application, date of award and duration of the license; and, in the case of production licenses, the commodity being produced.","name":"choice_1","order":1},{"criteria":"The country maintains a publicly available  register or cadastre system(s), but some essential information (described in full in Answer A) is missing (please explain) and/ or it is not computer-based.","name":"choice_2","order":2},{"criteria":"The country mainstains a register or cadastre system(s), but it is not publicly available. ","name":"choice_3","order":3},{"criteria":"The country does not maintain a publicly available register or cadastre system(s).","name":"choice_4","order":4},{"criteria":"Not applicable/Other. (Explain in 'comments' box.)","name":"choice_5","order":5}],question_text:"Does the country maintain a publicly available and computer-based register or cadastre system(s)?","component":"reporting","component_text":"Reporting practices"}),
			Question.create({question_text:"Does legislation require that mining, gas and oil development projects prepare an environmental impact assessment prior to the award of any mineral rights or project implementation and are there clear procedures (i.e. annual inspections)?",row_id_org:16,question_order:22,"question_choices":[{"criteria":"Yes. Legislation requires elaboration of an environmental impact assessment prior to the award of any mineral rights or project implementation and there are clear procedures (i.e. annual inspections).","name":"choice_1","order":1},{"criteria":"Legislation requires elaboration of an environmental impact assessment prior to the award of any mineral rights or project implementation, but there are no clear procedures (i.e. annual inspections).","name":"choice_2","order":2},{"criteria":"No. Legislation does not require preparation of an environmental impact assessment for mining, gas and oil projects.","name":"choice_3","order":3},{"criteria":"Not applicable/Other. (Explain in 'comments' box.)","name":"choice_4","order":4},{"criteria":" ","name":"choice_5","order":5}],"component":"institutional","component_text":"Institutional and legal setting","row_id":9}),
			Question.create({question_text:"Are environmental impact assessments for oil, gas and mining projects published by the authority in charge of regulating the sector?",row_id_org:17,question_order:23,"question_choices":[{"criteria":"Yes.  Environmental impact assessments for oil, gas and mining projects are made available for stakeholder review prior to awarding any mineral rights or project implementation and are published by the relevant authority.","name":"choice_1","order":1},{"criteria":"Yes. Environmental impact assessments for oil, gas and mining projects are published by the authority in charge of regulating the sector (or by other stakeholders such as companies), but only after approval by the relevant authority and not prior to awarding mineral rights or project implementation.","name":"choice_2","order":2},{"criteria":"No. Environmental impact assessments for oil, gas and mining projects are not published by the authority in charge of regulating the sector.","name":"choice_3","order":3},{"criteria":"Not applicable/Other. (Explain in 'comments' box.)","name":"choice_4","order":4}],"component":"reporting","component_text":"Reporting practices","row_id":10}),
			Question.create({question_text:"Does legislation require that mining, gas and oil development projects prepare a social impact assessment prior to the award of any mineral rights or project implementation and are there clear procedures (i.e. annual inspections)?",row_id_org:18,question_order:24,"question_choices":[{"criteria":"Yes. Legislation requires the preparation of a social impact assessment, prior to the award of any mineral rights or project implementation and there are clear procedures (i.e. annual inspections).","name":"choice_1","order":1},{"criteria":"Legislation requires the preparation of a social impact assessment, prior to the award of any mineral rights or project implementation, but there are no clear procedures (i.e. annual inspections).","name":"choice_2","order":2},{"criteria":"No. Legislation does not require the preparation of a social impact assessment for new mining, gas and oil projects.","name":"choice_3","order":3},{"criteria":"Not applicable/Other. (Explain in 'comments' box.)","name":"choice_4","order":4}],"component":"institutional","component_text":"Institutional and legal setting","row_id":11}),
			Question.create({question_text:"Are social impact assessments for oil, gas and mining projects published?",row_id_org:19,question_order:25,"question_choices":[{"criteria":"Yes. Social impact assessments for oil, gas and mining projects are made available for stakeholder review.","name":"choice_1","order":1},{"criteria":"Yes. Social impact assessments for oil, gas and mining projects are published by the authority in charge of regulating the sector (or by other stakeholders such as companies), but only after approval by the relevant authority and not prior to awarding mineral rights or project implementation.","name":"choice_2","order":2},{"criteria":"No.  Social impact assessments for oil, gas and mining projects are not published by the authority in charge of regulating the sector.","name":"choice_3","order":3},{"criteria":"Not applicable/Other. (Explain in 'comments' box.)","name":"choice_4","order":4}],"component":"reporting","component_text":"Reporting practices","row_id":12})
		}
	})
};

exports.createDefaultQuestions = createDefaultQuestions;