'use strict';
/*jslint nomen: true unparam: true*/

var mongoose = require('mongoose');

var ObjectId = mongoose.Schema.Types.ObjectId;
var Schemalesss = mongoose.Schema.Types.Mixed;

var modificationSchema = new mongoose.Schema({
    modifiedBy: Schemalesss, // Pull from curretn user _id value but needs to handle legacy comments
    modifiedDate: {type: Date, default: Date.now}
});

var commentSchema = new mongoose.Schema({
    date: {type: Date, default: Date.now},
    content: String,
    author: Schemalesss, // Pull from curretn user _id value but needs to handle legacy comments
    // author: ObjectId, // Pull from curretn user _id value but needs to handle legacy comments
    author_name: String,
    // ACTUAL CHANGE
    role: String
});

var questionSchema = mongoose.Schema({
    question_order: {type: Number, required: '{PATH} is required'},
    qid: String,
    old_reference: {
        row_id_org: String,
        row_id: String,
        old_rwi_questionnaire_code: String,
        uid: String,
        qid: String,
        indaba_question_order: String,
        component_excel: String,
        jan_2015_questionnaire_id: String,
        original_question_if_changed: String
    },
    component: {type: String, required: '{PATH} is required'},
    component_text: {type: String, required: '{PATH} is required'},
    broad_governance: String,
    rgi_mga: String,
    indicator: String,
    guidance_notes: String,
    year: String,
    version: String,
    root_question_ID: ObjectId,
    assessment_ID: {type: String, required: '{PATH} is required'},
    sub_indicator_namw: String,
    minstry_if_applicable: String,
    section_name: String,
    outcome_primary_q: String,
    child_question: String,
    needs_revision: Boolean,
    question_text : String,
    question_choices: [
        {
            name: String,
            order: Number,
            criteria: String
        }
    ],
    comments: [commentSchema],
    modified: [modificationSchema],
    precept: [Number]
});

var Question = mongoose.model('Question', questionSchema);

//function createDefaultQuestions() {
//    Question.find({}).exec(function (err, collection) {
//        if (collection.length === 0) {
//            Question.create({"precept" : [ 2 ], "indicator" : "EITI in national legislation", "question_text" : "Is the EITI ratified in national legislation?", "old_reference" : { "component_excel" : "Quality of legal structure" }, "question_choices" : [ { "criteria" : "Yes", "name" : "criteria_a", "order" : 1 }, { "criteria" : "Partial", "name" : "criteria_b", "order" : 2 }, { "criteria" : "No", "name" : "criteria_d", "order" : 3 }, { "criteria" : "Not applicable/other. (Explain in 'comments' box.)", "name" : "criteria_e", "order" : 4 } ], "component" : "legal", "modified" : [ ], "comments" : [ { "date" : ISODate("2015-06-23T21:27:39.494Z"), "content" : "needs revision", "author_name" : "From Excel file 'needs_revision' column.", "author" : "excel_reason" } ], "qid" : 14, "assessment_ID" : "base", "needs_revision" : true, "outcome_primary_q" : "Reporting, oversight and enforcement (precept 2 - Accountability and transparency)", "question_order" : 1, "component_text" : "Quality of legal structure", "options" : 4 });
//            Question.create({"precept" : [ 2 ], "indicator" : "Contract Disclosure", "question_text" : "Has this country adopted a rule or legisation that requires the publication of all contracts in the oil, gas, and mineral sectors?", "old_reference" : { "original_question_if_changed" : "Are all contracts, agreements or negotiated terms for exploration and production, regardless of the way they are granted, disclosed to the public?", "jan_2015_questionnaire_id" : "68", "component_excel" : "Quality of legal structure" }, "question_choices" : [ { "criteria" : "Yes", "name" : "criteria_a", "order" : 1 }, { "criteria" : "Partial", "name" : "criteria_b", "order" : 2 }, { "criteria" : "No", "name" : "criteria_d", "order" : 3 }, { "criteria" : "Not applicable/other. (Explain in 'comments' box.)", "name" : "criteria_e", "order" : 4 } ], "component" : "legal", "modified" : [ ], "comments" : [ { "date" : ISODate("2015-06-23T21:27:39.494Z"), "content" : "needs revision", "author_name" : "From Excel file 'needs_revision' column.", "author" : "excel_reason" }, { "date" : ISODate("2015-06-23T21:27:39.494Z"), "content" : "EITI includes RGI - 3.12.b: Report includes the government's policy on contract and license disclosure, including: Relevant legal provisions; Actual disclosure practices; Nay reforms that are planned or underway; If applicable, an overview of the contracts and licenses that are publicly available// Encouraged element - 3.12a:  Country discloses extractive contracts", "author_name" : "From Excel file 'eiti' column.", "author" : "excel_reason" } ], "qid" : 15, "assessment_ID" : "base", "needs_revision" : true, "outcome_primary_q" : "Reporting, oversight and enforcement (precept 2 - Accountability and transparency)", "question_order" : 2, "component_text" : "Quality of legal structure", "options" : 4 });
//            Question.create({"precept" : [ 2 ], "indicator" : "Contract Disclosure", "question_text" : "Have all contracts between extraction companies and the government been disclosed?", "old_reference" : { "component_excel" : "Reporting practice" }, "question_choices" : [ { "criteria" : "Yes, in pdf, online.", "name" : "criteria_a", "order" : 1 }, { "criteria" : "Yes, but only physical copies", "name" : "criteria_b", "order" : 2 }, { "criteria" : "No", "name" : "criteria_d", "order" : 3 }, { "criteria" : "Not applicable/other. (Explain in 'comments' box.)", "name" : "criteria_e", "order" : 4 } ], "component" : "reporting", "modified" : [ ], "comments" : [ { "date" : ISODate("2015-06-23T21:27:39.494Z"), "content" : "There is probably an equivalent Q in RGI 2013", "author_name" : "From Excel file 'design_issues' column.", "author" : "excel_reason" } ], "assessment_ID" : "base", "needs_revision" : false, "question_order" : 3, "component_text" : "Reporting practice", "options" : 4 });
//            Question.create({"precept" : [ 2 ], "indicator" : "Freedom of Information law applied", "question_text" : "Do citizens request and successfully receive information using the freedom of information law?", "old_reference" : { "component_excel" : "Oversight" }, "question_choices" : [ { "criteria" : "Yes", "name" : "criteria_a", "order" : 1 }, { "criteria" : "Partial", "name" : "criteria_b", "order" : 2 }, { "criteria" : "No", "name" : "criteria_d", "order" : 3 }, { "criteria" : "Not applicable/other. (Explain in 'comments' box.)", "name" : "criteria_e", "order" : 4 } ], "component" : "oversight", "modified" : [ ], "comments" : [ ], "qid" : 16, "assessment_ID" : "base", "needs_revision" : false, "outcome_primary_q" : "Reporting, oversight and enforcement (precept 2 - Accountability and transparency)", "question_order" : 4, "component_text" : "Oversight", "options" : 4 });
//            Question.create({"precept" : [ 2 ], "indicator" : "EITI report", "question_text" : "Has this country published an EITI report?", "old_reference" : { "jan_2015_questionnaire_id" : "64", "component_excel" : "Reporting practice" }, "question_choices" : [ { "criteria" : "The country has published an EITI report, including information on national revenue classification systems and international standards, such as the IMF Government Finance Statistics Manual; a summary of national audit procedures (including an analysis of whether audit procedures meet international standards); information about the contribution of the extractive industries to the economy for the year covered (including: size of the extractive industries in absolute terms, size of the extractive industries as percentage of GDP, an estimate of informal sector activity); exports from the extractive industries in absolute terms; exports from the extractive industries as percentage of total exports.", "name" : "criteria_a", "order" : 1 }, { "criteria" : "The country has published an EITI report, but some essential information (described in full in Answer A) is missing (please explain).", "name" : "criteria_b", "order" : 2 }, { "criteria" : "The country has published an EITI report with only scant information.", "name" : "criteria_c", "order" : 3 }, { "criteria" : "The country has not published an EITI report.", "name" : "criteria_d", "order" : 4 }, { "criteria" : "Not applicable/Other. (Explain in 'comments' box.)", "name" : "criteria_e", "order" : 5 } ], "component" : "reporting", "modified" : [ ], "comments" : [ { "date" : ISODate("2015-06-23T21:27:39.494Z"), "content" : "3.7b**", "author_name" : "From Excel file 'eiti' column.", "author" : "excel_reason" } ], "qid" : 17, "assessment_ID" : "base", "needs_revision" : false, "outcome_primary_q" : "Reporting, oversight and enforcement (precept 2 - Accountability and transparency)", "guidance_notes" : "Record link to document.", "question_order" : 5, "component_text" : "Reporting practice", "options" : 5 });
//            Question.create({"precept" : [ 2 ], "indicator" : "Quality of EITI data", "question_text" : "If the country has published an EITI report, does it cover all topics in new standard?", "old_reference" : { "component_excel" : "Reporting practice" }, "question_choices" : [ { "criteria" : "Covers all topics relevant within country context", "name" : "criteria_a", "order" : 1 }, { "criteria" : "Only includes resource revenue reconciliation", "name" : "criteria_c", "order" : 2 }, { "criteria" : "The country has not published an EITI report.", "name" : "criteria_d", "order" : 3 }, { "criteria" : "Not applicable/Other. (Explain in 'comments' box.)", "name" : "criteria_e", "order" : 4 } ], "component" : "reporting", "modified" : [ ], "comments" : [ ], "qid" : 18, "assessment_ID" : "base", "needs_revision" : false, "outcome_primary_q" : "Reporting, oversight and enforcement (precept 2 - Accountability and transparency)", "guidance_notes" : "Record link to document.", "question_order" : 6, "component_text" : "Reporting practice", "options" : 4 });
//            Question.create({"precept" : [ 2 ], "indicator" : "Quality of EITI data", "question_text" : "If the country has published an EITI report, does it include project-level reporting", "old_reference" : { "component_excel" : "Reporting practice" }, "question_choices" : [ { "criteria" : "Project level information available.", "name" : "criteria_a", "order" : 1 }, { "criteria" : "No project level reporting.", "name" : "criteria_c", "order" : 2 }, { "criteria" : "The country has not published an EITI report.", "name" : "criteria_d", "order" : 3 }, { "criteria" : "Not applicable/Other. (Explain in 'comments' box.)", "name" : "criteria_e", "order" : 4 } ], "component" : "reporting", "modified" : [ ], "comments" : [ ], "qid" : 19, "assessment_ID" : "base", "needs_revision" : false, "outcome_primary_q" : "Reporting, oversight and enforcement (precept 2 - Accountability and transparency)", "question_order" : 7, "component_text" : "Reporting practice", "options" : 4 });
//            Question.create({"precept" : [ 2 ], "indicator" : "Quality of EITI data", "question_text" : "If the country has published an EITI report, is it available within reasonable time lag?", "old_reference" : { "component_excel" : "Reporting practice" }, "question_choices" : [ { "criteria" : "Yes, within a year of completion of financial year.", "name" : "criteria_a", "order" : 1 }, { "criteria" : "More than 2 year lag.", "name" : "criteria_c", "order" : 2 }, { "criteria" : "The country has not published an EITI report.", "name" : "criteria_d", "order" : 3 }, { "criteria" : "Not applicable/Other. (Explain in 'comments' box.)", "name" : "criteria_e", "order" : 4 } ], "component" : "reporting", "modified" : [ ], "comments" : [ ], "qid" : 20, "assessment_ID" : "base", "needs_revision" : false, "outcome_primary_q" : "Reporting, oversight and enforcement (precept 2 - Accountability and transparency)", "question_order" : 8, "component_text" : "Reporting practice", "options" : 4 });
//            Question.create({"precept" : [ 2 ], "indicator" : "Quality of EITI data", "question_text" : "If the country has published an EITI report, is it available in machine readable format?", "old_reference" : { "component_excel" : "Reporting practice" }, "question_choices" : [ { "criteria" : "Yes, available to download in Excel and under open data license. Report and data files are coded or tagged .", "name" : "criteria_a", "order" : 1 }, { "criteria" : "Excel file is available alongside PDF", "name" : "criteria_b", "order" : 2 }, { "criteria" : "No. PDF.", "name" : "criteria_c", "order" : 3 }, { "criteria" : "The country has not published an EITI report.", "name" : "criteria_d", "order" : 4 }, { "criteria" : "Not applicable/Other. (Explain in 'comments' box.)", "name" : "criteria_e", "order" : 5 } ], "component" : "reporting", "modified" : [ ], "comments" : [ { "date" : ISODate("2015-06-23T21:27:39.494Z"), "content" : "5.3b Electronic data files are produced along with the report", "author_name" : "From Excel file 'eiti' column.", "author" : "excel_reason" } ], "qid" : 21, "assessment_ID" : "base", "needs_revision" : false, "outcome_primary_q" : "Reporting, oversight and enforcement (precept 2 - Accountability and transparency)", "question_order" : 9, "component_text" : "Reporting practice", "options" : 5 });
//            Question.create({"precept" : [ 1 ], "indicator" : "Data of natural capital accounting", "question_text" : "Does the government disclose comprehensive data on the depletion of its natural capital? (reserves, sales, export)", "old_reference" : { "jan_2015_questionnaire_id" : "82 - 141", "component_excel" : "Reporting practice" }, "question_choices" : [ { "criteria" : "Yes, the government provides comprehensive information including reserves stock and change, total production/export volume and value for most important commodity.", "name" : "criteria_a", "order" : 1 }, { "criteria" : "Either  reserves, volume or value of production of key commodities is not available.", "name" : "criteria_c", "order" : 2 }, { "criteria" : "Information on reserves, volume and value of production/export of key commodities is not available.", "name" : "criteria_d", "order" : 3 }, { "criteria" : "Not applicable/Other. (Explain in 'comments' box.)", "name" : "criteria_e", "order" : 4 } ], "component" : "reporting", "modified" : [ ], "comments" : [ { "date" : ISODate("2015-06-23T21:27:39.495Z"), "content" : "Move to P1", "author_name" : "From Excel file 'design_issues' column.", "author" : "excel_reason" }, { "date" : ISODate("2015-06-23T21:27:39.495Z"), "content" : "needs revision", "author_name" : "From Excel file 'needs_revision' column.", "author" : "excel_reason" }, { "date" : ISODate("2015-06-23T21:27:39.495Z"), "content" : "3.5a,  3.5b -Production and export volumes/values by commodity by state/region (if applicable)", "author_name" : "From Excel file 'eiti' column.", "author" : "excel_reason" } ], "qid" : 22, "assessment_ID" : "base", "needs_revision" : true, "outcome_primary_q" : "Reporting, oversight and enforcement (precept 2 - Accountability and transparency)", "guidance_notes" : "Record link to document. Record if disclosed in EITI report.", "question_order" : 10, "component_text" : "Reporting practice", "options" : 4 });
//            Question.create({"precept" : [ 1 ], "indicator" : "Data of natural capital accounting", "question_text" : "Does the government disclose disaggregated data on the depletion of its natural capital? (reserves, sales, export)", "old_reference" : { "jan_2015_questionnaire_id" : "82 - 141", "component_excel" : "Reporting practice" }, "question_choices" : [ { "criteria" : "Yes this information is available for multiple commodities and by state/region where applicable.", "name" : "criteria_a", "order" : 1 }, { "criteria" : "The information is available for one key commodity, but not some other significant commodity with breakdown by state/regione.", "name" : "criteria_b", "order" : 2 }, { "criteria" : "The information is available for one key commodity, but not some other significant commodity with no breakdown by state/region.", "name" : "criteria_c", "order" : 3 }, { "criteria" : "Information on reserves, volume and value of production/export of key commodities is not available.", "name" : "criteria_d", "order" : 4 }, { "criteria" : "Not applicable/Other. (Explain in 'comments' box.)", "name" : "criteria_e", "order" : 5 } ], "component" : "reporting", "modified" : [ ], "comments" : [ { "date" : ISODate("2015-06-23T21:27:39.495Z"), "content" : "3.5a,  3.5b -Production and export volumes/values by commodity by state/region (if applicable)", "author_name" : "From Excel file 'eiti' column.", "author" : "excel_reason" } ], "qid" : 23, "assessment_ID" : "base", "needs_revision" : false, "outcome_primary_q" : "Reporting, oversight and enforcement (precept 2 - Accountability and transparency)", "question_order" : 11, "component_text" : "Reporting practice", "options" : 5 });
//            Question.create({"precept" : [ 1 ], "indicator" : "Data of natural capital accounting", "question_text" : "Does the government disclose timely data on the depletion of its natural capital? (reserves, sales, export)", "old_reference" : { "jan_2015_questionnaire_id" : "82 - 141", "component_excel" : "Reporting practice" }, "question_choices" : [ { "criteria" : "Yes, within a year lag.", "name" : "criteria_a", "order" : 1 }, { "criteria" : "Over two year lag.", "name" : "criteria_c", "order" : 2 }, { "criteria" : "Information on reserves, volume and value of production/export of key commodities is not available.", "name" : "criteria_d", "order" : 3 }, { "criteria" : "Not applicable/Other. (Explain in 'comments' box.)", "name" : "criteria_e", "order" : 4 } ], "component" : "reporting", "modified" : [ ], "comments" : [ { "date" : ISODate("2015-06-23T21:27:39.495Z"), "content" : "3.5a,  3.5b -Production and export volumes/values by commodity by state/region (if applicable)", "author_name" : "From Excel file 'eiti' column.", "author" : "excel_reason" } ], "qid" : 24, "assessment_ID" : "base", "needs_revision" : false, "outcome_primary_q" : "Reporting, oversight and enforcement (precept 2 - Accountability and transparency)", "question_order" : 12, "component_text" : "Reporting practice", "options" : 4 });
//            Question.create({"precept" : [ 1 ], "indicator" : "Data of natural capital accounting", "question_text" : "Does the government disclose machine readable data on the depletion of its natural capital? (reserves, sales, export)", "old_reference" : { "jan_2015_questionnaire_id" : "82 - 141", "component_excel" : "Reporting practice" }, "question_choices" : [ { "criteria" : "Yes, available to download in Excel and under open data license.", "name" : "criteria_a", "order" : 1 }, { "criteria" : "PDF reporting.", "name" : "criteria_c", "order" : 2 }, { "criteria" : "Information on reserves, volume and value of production/export of key commodities is not available.", "name" : "criteria_d", "order" : 3 }, { "criteria" : "Not applicable/Other. (Explain in 'comments' box.)", "name" : "criteria_e", "order" : 4 } ], "component" : "reporting", "modified" : [ ], "comments" : [ { "date" : ISODate("2015-06-23T21:27:39.495Z"), "content" : "3.5a,  3.5b -Production and export volumes/values by commodity by state/region (if applicable)", "author_name" : "From Excel file 'eiti' column.", "author" : "excel_reason" } ], "qid" : 25, "assessment_ID" : "base", "needs_revision" : false, "outcome_primary_q" : "Reporting, oversight and enforcement (precept 2 - Accountability and transparency)", "question_order" : 13, "component_text" : "Reporting practice", "options" : 4 });
//            Question.create({"precept" : [ 2 ], "indicator" : "EITI participation", "question_text" : "Is the country EITI compliant?", "old_reference" : { "jan_2015_questionnaire_id" : "34", "component_excel" : "Oversight" }, "question_choices" : [ { "criteria" : "The country is EITI compliant.", "name" : "criteria_a", "order" : 1 }, { "criteria" : "The country is an EITI candidate country or has published an EITI report.", "name" : "criteria_b", "order" : 2 }, { "criteria" : "The country is not implementing the EITI and has not expressed interest to implement this initiative.", "name" : "criteria_c", "order" : 3 }, { "criteria" : "The country has been delisted from the EITI process.", "name" : "criteria_d", "order" : 4 }, { "criteria" : "Not applicable/Other. (Explain in 'comments' box.)", "name" : "criteria_e", "order" : 5 } ], "component" : "oversight", "modified" : [ ], "comments" : [ { "date" : ISODate("2015-06-23T21:27:39.495Z"), "content" : "N/A", "author_name" : "From Excel file 'eiti' column.", "author" : "excel_reason" } ], "qid" : 26, "assessment_ID" : "base", "needs_revision" : false, "outcome_primary_q" : "Reporting, oversight and enforcement (precept 2 - Accountability and transparency)", "question_order" : 14, "component_text" : "Oversight", "options" : 5 });
//            Question.create({"precept" : [ 2 ], "indicator" : "Government disclosure of conflicts of interest", "question_text" : "Are government officials with a role in the oversight of the oil, gas or mining sector required to disclose information about their financial interest in any extractive activities or projects and  is this applied in practice?", "old_reference" : { "jan_2015_questionnaire_id" : "267", "component_excel" : "Oversight" }, "question_choices" : [ { "criteria" : "Yes. Government officials with a role in the oversight of oil, gas or mining sectors are required to disclose information about their participation in extractive activities or projects.", "name" : "criteria_a", "order" : 1 }, { "criteria" : "Partial", "name" : "criteria_b", "order" : 2 }, { "criteria" : "No. Government officials are not required to disclose this kind of information.", "name" : "criteria_d", "order" : 3 }, { "criteria" : "Not applicable/other. (Explain in 'comments' box.)", "name" : "criteria_e", "order" : 4 } ], "component" : "oversight", "modified" : [ ], "comments" : [ { "date" : ISODate("2015-06-23T21:27:39.495Z"), "content" : "We should aslo ask whether this requirement is applied in practice", "author_name" : "From Excel file 'design_issues' column.", "author" : "excel_reason" }, { "date" : ISODate("2015-06-23T21:27:39.495Z"), "content" : "needs revision", "author_name" : "From Excel file 'needs_revision' column.", "author" : "excel_reason" }, { "date" : ISODate("2015-06-23T21:27:39.495Z"), "content" : "N/A", "author_name" : "From Excel file 'eiti' column.", "author" : "excel_reason" } ], "qid" : 27, "assessment_ID" : "base", "needs_revision" : true, "outcome_primary_q" : "Reporting, oversight and enforcement (precept 2 - Accountability and transparency)", "question_order" : 15, "component_text" : "Oversight", "options" : 4 });
//            Question.create({"precept" : [ 2 ], "indicator" : "Online data portal", "question_text" : "Is there an online data portal where natural resource sector information can be found in one place?", "old_reference" : { "component_excel" : "Oversight" }, "question_choices" : [ { "criteria" : "Yes. It is comprehensive, all data identified in questions below are also available on this portal.", "name" : "criteria_a", "order" : 1 }, { "criteria" : "Yes, but limited availability of resource sector data.", "name" : "criteria_b", "order" : 2 }, { "criteria" : "Yes, but resource sector data not included.", "name" : "criteria_c", "order" : 3 }, { "criteria" : "No such portal.", "name" : "criteria_d", "order" : 4 }, { "criteria" : "Not applicable/other. (Explain in 'comments' box.)", "name" : "criteria_e", "order" : 5 } ], "component" : "oversight", "modified" : [ ], "comments" : [ ], "qid" : 28, "assessment_ID" : "base", "needs_revision" : false, "outcome_primary_q" : "Reporting, oversight and enforcement (precept 2 - Accountability and transparency)", "question_order" : 16, "component_text" : "Oversight", "options" : 5 });
//            Question.create({"precept" : [ 2 ], "indicator" : "Online data portal", "question_text" : "Is the online data portal up to date?", "old_reference" : { "component_excel" : "Oversight" }, "question_choices" : [ { "criteria" : "Yes, data is available with less than a year lag.", "name" : "criteria_a", "order" : 1 }, { "criteria" : "1-2 year lag.", "name" : "criteria_b", "order" : 2 }, { "criteria" : "More than 2 year old data", "name" : "criteria_c", "order" : 3 }, { "criteria" : "No such portal.", "name" : "criteria_d", "order" : 4 }, { "criteria" : "Not applicable/other. (Explain in 'comments' box.)", "name" : "criteria_e", "order" : 5 } ], "component" : "oversight", "modified" : [ ], "comments" : [ ], "qid" : 29, "assessment_ID" : "base", "needs_revision" : false, "outcome_primary_q" : "Reporting, oversight and enforcement (precept 2 - Accountability and transparency)", "question_order" : 17, "component_text" : "Oversight", "options" : 5 });
//            Question.create({"precept" : [ 2 ], "indicator" : "Online data portal", "question_text" : "Is the online data portal meeting open data standards?", "old_reference" : { "component_excel" : "Oversight" }, "question_choices" : [ { "criteria" : "Yes, data is available through an API, machine readable and has an open license.", "name" : "criteria_a", "order" : 1 }, { "criteria" : "Data has either restricted access (limited download) or license.", "name" : "criteria_b", "order" : 2 }, { "criteria" : "Data has restrictive access and license.", "name" : "criteria_c", "order" : 3 }, { "criteria" : "No such portal.", "name" : "criteria_d", "order" : 4 }, { "criteria" : "Not applicable/other. (Explain in 'comments' box.)", "name" : "criteria_e", "order" : 5 } ], "component" : "oversight", "modified" : [ ], "comments" : [ ], "qid" : 30, "assessment_ID" : "base", "needs_revision" : false, "outcome_primary_q" : "Reporting, oversight and enforcement (precept 2 - Accountability and transparency)", "question_order" : 18, "component_text" : "Oversight", "options" : 5 });
//            Question.create({"precept" : [ 3 ], "indicator" : "Rules defining ownership of data", "question_text" : "Has this country adopted a rule or legisation that requires companies to share geodata with the government?", "old_reference" : { "component_excel" : "Quality of legal structure" }, "question_choices" : [ { "criteria" : "Yes, During exploration a requirement for companies to report quantitative operational information (number of workers employed, metres trenched or drilled, samples taken, etc.) regularly (quarterly, for instance) and for this to be confirmed by external audits annually. Then to release technical information (analytical values, geological/geophysical/geochemical maps, estimated resources, etc.) when an exploration program is terminated, or when application is made to convert part of the license to a mining lease. During mining, regular technical reports should also be made, so as to help determine production levels and taxes due, etc.", "name" : "criteria_a", "order" : 1 }, { "criteria" : "Partial, rules exist but do not cover all requirements listed in criteria A.", "name" : "criteria_b", "order" : 2 }, { "criteria" : "No, the coutry does not have a rule requiring sharing of geo data.", "name" : "criteria_d", "order" : 3 }, { "criteria" : "Not applicable/other. (Explain in 'comments' box.)", "name" : "criteria_e", "order" : 4 } ], "component" : "legal", "modified" : [ ], "comments" : [ ], "qid" : 35, "rgi_mga" : "MGA", "assessment_ID" : "base", "needs_revision" : false, "outcome_primary_q" : "3.1 Geological Information. Does government manage geological information in a way that enhances competition, improves its negotiating position and manages the resource?", "guidance_notes" : "Evidence: Regulations and guidelines from GSD/MCO/Ministry. \n\nBest practice: During exploration would be a requirement for companies to report quantitative operational information (number of workers employed, metres trenched or drilled, samples taken, etc.) regularly (quarterly, for instance) and for this to be confirmed by external audits annually. Then to release technical information (analytical values, geological/geophysical/geochemical maps, estimated resources, etc.) when an exploration program is terminated, or when application is made to convert part of the license to a mining lease. During mining, regular technical reports should also be made, so as to help determine production levels and taxes due, etc.", "question_order" : 19, "component_text" : "Quality of legal structure", "options" : 4 });
//            Question.create({"precept" : [ 3 ], "indicator" : "Clear and comprehensive license allocation rules", "question_text" : "Does the licensing process specify minimum pre-defined evaluation criteria for all qualified companies?", "old_reference" : { "original_question_if_changed" : "Is the licensing process intended to be open and competitive to all qualified companies?", "jan_2015_questionnaire_id" : "36", "component_excel" : "Quality of legal structure" }, "question_choices" : [ { "criteria" : "Yes. Laws specify minium pre-defined criteria for qualification of companies, and there are not onerous laws prohibiting financially and technically capable companies from seeking qualification.", "name" : "criteria_a", "order" : 1 }, { "criteria" : "Yes. Laws specify minium pre-defined criteria for qualification of companies, BUT there are not onerous laws prohbiting financially and technically capable companies from seeking qualification.", "name" : "criteria_b", "order" : 2 }, { "criteria" : "There are neither minimum qualification criteria, but nor is there onerous laws prohibiting capacble companies", "name" : "criteria_c", "order" : 3 }, { "criteria" : "No. The licensing process or other laws limits participation of qualified companies based on discretionary rules ...", "name" : "criteria_d", "order" : 4 }, { "criteria" : "Not applicable/Other. (Explain in 'comments' box.)", "name" : "criteria_e", "order" : 5 } ], "component" : "legal", "modified" : [ ], "comments" : [ { "date" : ISODate("2015-06-23T21:27:39.495Z"), "content" : "3.10a - Report includes a description of the process for transferring or awarding licenses, including:The technical and financial criteria usedInformation about the recipient(s) of the license, including consortium members where applicableAny non-trivial deviations from\nthe applicable legal and regulatory framework governing license transfers and awards", "author_name" : "From Excel file 'eiti' column.", "author" : "excel_reason" } ], "qid" : 38, "rgi_mga" : "RGI", "assessment_ID" : "base", "needs_revision" : false, "outcome_primary_q" : "3.3 Choosing companies. Does the government allocate rights to the most financially and technically competent companies available?", "question_order" : 20, "component_text" : "Quality of legal structure", "options" : 5 });
//            //Question.create({"assessment_ID": "base", "precept": 1, "question_text": "Does the country have a clear legal definition of ownership of mineral resources?", "old_reference": {"row_id": "1", "row_id_org": "4", "component_excel": "NULL"}, "indicator_name": "Ownership rights", "ministry": "none", "question_choices": [{"criteria": "The constitution and national laws grant ownership of all mineral resources in the ground to the sovereign state. The legislation does not recognize or guarantee private property rights over resources in the ground.", "name": "choice_1", "order": 1}, {"criteria": "The constitution and national laws recognize or guarantee private property rights over mineral resources in the ground, with the exception of state-owned land.", "name": "choice_2", "order": 2}, {"criteria": "The constitution and national laws give ownership of mineral resources in the ground to subnational governments, agencies or to indigenous groups.", "name": "choice_3", "order": 3}, {"criteria": "The constitution and national laws recognize a mix of ownership rights.", "name": "choice_4", "order": 4}, {"criteria": "Not applicable/Other. (Explain in 'comments' box.)", "name": "choice_5", "order": 5}], "component": "context", "modified": [{"modifiedBy": "initiated", "modifiedDate": null}], "comments": [{"date": null, "content": "N/A", "author_name": "From Excel file 'EITI' column.", "author": "excel_eiti"}], "component_text": "Context", "section_name": "Access to Resources", "question_order": 1, "sub_indicator_name": "NULL", "options": 5});
//            //Question.create({"assessment_ID": "base", "precept": 3, "question_text": "Who has the authority to grant hydrocarbon and mineral rights or licenses?", "old_reference": {"row_id": "2", "row_id_org": "5", "component_excel": "NULL"}, "indicator_name": "Licensing Authority", "ministry": "none", "question_choices": [{"criteria": "The ministry of the extractive sector.", "name": "choice_1", "order": 1}, {"criteria": "A technical agency or regulator.", "name": "choice_2", "order": 2}, {"criteria": "A state-owned company.", "name": "choice_3", "order": 3}, {"criteria": "The office of the executive.", "name": "choice_4", "order": 4}, {"criteria": "Not applicable/Other. (Explain in 'comments' box.)", "name": "choice_5", "order": 5}], "component": "context", "modified": [{"modifiedBy": "initiated", "modifiedDate": null}], "comments": [{"date": null, "content": "RGI includes EITI - 3.10.a: Report includes a description of the process for transferring or awarding licenses", "author_name": "From Excel file 'EITI' column.", "author": "excel_eiti"}, {"date": null, "content": "ML: The EITI stnadard requires to describe the legal framework and fiscal regime, which includes a description of who has authority to grant licenses.\n\nDMa. Could add a related question on clarity and simplicity of license grant process. \"is there only one authority that grants hydrocarbon and mineral rights and licenses?\"\n\nBut worth checking with Amir whether this is always a good thing. Might want to nuance a bit and ask whether there is no overlapping authority between areas for licensing.", "author_name": "From Excel file 'Comments' column.", "author": "excel_comments"}], "component_text": "Context", "section_name": "Access to Resources", "question_order": 2, "sub_indicator_name": "NULL", "options": 5});
//            //Question.create({"assessment_ID": "base", "precept": 3, "question_text": "What licensing practices does the government commonly follow?", "old_reference": {"row_id": "3", "row_id_org": "6", "component_excel": "NULL"}, "indicator_name": "Licensing Authority", "ministry": "none", "question_choices": [{"criteria": "The government conducts open bidding rounds with sealed bid process and decision is made against established criteria (e.g. open bidding rounds can be either with fixed royalty rates and taxes but on the basis of work programs and expenditures, or on variable parameters such as bonuses, royalty rates, profit oil splits and cost recovery limits).", "name": "choice_1", "order": 1}, {"criteria": "The government grants mineral rights following direct negotiations.", "name": "choice_2", "order": 2}, {"criteria": "The government follows the rule of \u201cfirst-come, first-served\u201d to grant mineral licenses, while royalties and taxes are set by legislation.", "name": "choice_3", "order": 3}, {"criteria": "This country does not license mineral rights to private companies.", "name": "choice_4", "order": 4}, {"criteria": "Not applicable/Other. (Explain in 'comments' box.)", "name": "choice_5", "order": 5}], "component": "context", "modified": [{"modifiedBy": "initiated", "modifiedDate": null}], "comments": [{"date": null, "content": "RGI includes EITI - 3.10.a: Report includes a description of the process for transferring or awarding licenses", "author_name": "From Excel file 'EITI' column.", "author": "excel_eiti"}, {"date": null, "content": "DMa. This question could be improved to reflect my comment above", "author_name": "From Excel file 'Comments' column.", "author": "excel_comments"}], "component_text": "Context", "section_name": "Access to Resources", "question_order": 3, "sub_indicator_name": "NULL", "options": 5});
//            //Question.create({"assessment_ID": "base", "precept": 4, "question_text": "What is the fiscal system for mineral resources?", "old_reference": {"row_id": "4", "row_id_org": "7", "component_excel": "NULL"}, "indicator_name": "Fiscal System Minerals", "ministry": "none", "question_choices": [{"criteria": "Companies receive licenses or concessions to explore, exploit and sell minerals in exchange for royalties and taxes.", "name": "choice_1", "order": 1}, {"criteria": "Companies sign production sharing agreements that determine payments and sharing of costs and profits with the government.", "name": "choice_2", "order": 2}, {"criteria": "Companies sign service contracts that determine a fee for services delivered to government agencies.", "name": "choice_3", "order": 3}, {"criteria": "There is a mixed system, which allows different agreements, contracts or regimes to take place, depending on the government's objectives.", "name": "choice_4", "order": 4}, {"criteria": "Not applicable/Other. (Explain in 'comments' box.)", "name": "choice_5", "order": 5}], "component": "context", "modified": [{"modifiedBy": "initiated", "modifiedDate": null}], "comments": [{"date": null, "content": "RGI overlaps with EITI - 3.2.a and b: Summary of fiscal regime, including: Level of fiscal devolution; overview of the relevant laws and regulations; Information on the roles and responsibilities of the relevant government agencies/ Reforms currently under way (if applicable)", "author_name": "From Excel file 'EITI' column.", "author": "excel_eiti"}, {"date": null, "content": "DMa. I don\u2019t really see the point in this question.", "author_name": "From Excel file 'Comments' column.", "author": "excel_comments"}], "component_text": "Context", "section_name": "Access to Resources", "question_order": 4, "sub_indicator_name": "NULL", "options": 5});
//        }
//    });
//}
//
//exports.createDefaultQuestions = createDefaultQuestions;
