EnvironmentConfigurationMetadata:
  Description: Configuration created from the EB CLI using "eb config save".
  DateModified: '1436538617000'
  DateCreated: '1436538617000'
AWSConfigurationTemplateVersion: 1.1.0.0
EnvironmentTier:
  Name: WebServer
  Type: Standard
SolutionStack: 64bit Amazon Linux 2015.03 v1.3.1 running Docker 1.5.0
OptionSettings:
  aws:elb:loadbalancer:
    CrossZone: true
  aws:elasticbeanstalk:command:
    BatchSize: '30'
    BatchSizeType: Percentage
  aws:autoscaling:launchconfiguration:
    IamInstanceProfile: aws-elasticbeanstalk-ec2-role
    EC2KeyName: rgi-tool
    InstanceType: t2.micro
  aws:elb:policies:
    ConnectionDrainingEnabled: true
  aws:autoscaling:updatepolicy:rollingupdate:
    RollingUpdateType: Health
    RollingUpdateEnabled: true
  aws:elasticbeanstalk:application:environment:
    DB_ID: cperry
    DB_KEY: 50Crat3s
    DOC_AWS_ACCESS_KEY: AKIAJ3T6AQQTDB3CXX7Q
    DOC_AWS_SECRET_KEY: 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
    NEWRELIC_APP_NAME: RGI Assessment Tool Dev
    DOC_BUCKET: rgi_documents_dev
    NODE_ENV: development
    MANDRILL_APIKEY: 7DmKOv-FBAcqpO5NltSPsA
    NEWRELIC_KEY: 69a422448cd1ac990ca9c367a0e486853a2afa61
  aws:elb:healthcheck:
    Interval: '30'
